"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Client = exports.Service = exports.Response = exports.Request = exports.NotImplemented = exports.NotSupportedMethod = exports.isSpecterError = exports.isSpecterNetworkError = exports.SpecterNetworkError = void 0;
var tslib_1 = require("tslib");
var specter_1 = (0, tslib_1.__importDefault)(require("./specter"));
var request_1 = (0, tslib_1.__importDefault)(require("./request"));
exports.Request = request_1.default;
var response_1 = (0, tslib_1.__importDefault)(require("./response"));
exports.Response = response_1.default;
var service_1 = (0, tslib_1.__importDefault)(require("./service"));
exports.Service = service_1.default;
var client_1 = (0, tslib_1.__importDefault)(require("./client"));
exports.Client = client_1.default;
var errors_1 = require("./errors");
Object.defineProperty(exports, "SpecterNetworkError", { enumerable: true, get: function () { return errors_1.SpecterNetworkError; } });
Object.defineProperty(exports, "isSpecterNetworkError", { enumerable: true, get: function () { return errors_1.isSpecterNetworkError; } });
Object.defineProperty(exports, "isSpecterError", { enumerable: true, get: function () { return errors_1.isSpecterError; } });
Object.defineProperty(exports, "NotSupportedMethod", { enumerable: true, get: function () { return errors_1.NotSupportedMethod; } });
Object.defineProperty(exports, "NotImplemented", { enumerable: true, get: function () { return errors_1.NotImplemented; } });
exports.default = specter_1.default;
